### ISSUE TITLE
"Test if mount_requests is set correctly" on empty list

### ISSUE THREAD

**Issue by debuglevel** [robertdebock/ansible-role-mount#1]
## Proposed feature

I think it would be better if `mount_requests` is allowed to be an empty list (or something the like).
That way, I could just configure an empty variable for hosts which should not have additional mounts.
For now, I have to introduce a new group or do a `when` on my own.

**Comment by debuglevel** [comment]
Additionally as the `assert.yaml` has `run_once: yes` (and maybe `delegate_to: localhost`?) this seems to have an odd behavior if defined per host or group. But maybe I'm doing some bad practice here...

**Comment by robertdebock** [comment]
Thanks, `mount_requests` should be optional indeed. Changed with the last commit.

The `assert.yml` (which checks variables) runs on localhost (to speed up the checks) and indeed `run_once`. Please let me know what issues you are running into. Likely in a new issue.

Thanks @debuglevel
