### ISSUE TITLE
Relax accepted fstype restriction in mount_requests

### ISSUE THREAD

**Issue by privatewright** [robertdebock/ansible-role-mount#2]
## Proposed feature

Relax the accepted fstype restriction for mount_requests.

## Rationale

Currently, as stated in assert.yml, fstype for mount_requests must strictly be  "ext3", "ext4", "iso9660", "nfs", "none", "swap", or "xfs". This leads to assertion error when setting fstype to file systems such as btrfs, fuse-type filesystem, glusterfs, etc.

## Additional context

I understand the rationale for default file system type a fallback for the user. Perhaps a toggle or some sort to bypass it may suffice?

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by robertdebock** [comment]
Good one, let me zoom in and think of something. Maybe a warning-message instead of a failure.
